package ufg.inf.pw.model;
// Generated Apr 30, 2015 2:48:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aviamento generated by hbm2java
 */
public class Aviamento  implements java.io.Serializable {


     private int idaviamento;
     private String nome;
     private String unidadeMedida;
     private Set faccaos = new HashSet(0);

    public Aviamento() {
    }

	
    public Aviamento(int idaviamento) {
        this.idaviamento = idaviamento;
    }
    public Aviamento(int idaviamento, String nome, String unidadeMedida, Set faccaos) {
       this.idaviamento = idaviamento;
       this.nome = nome;
       this.unidadeMedida = unidadeMedida;
       this.faccaos = faccaos;
    }
   
    public int getIdaviamento() {
        return this.idaviamento;
    }
    
    public void setIdaviamento(int idaviamento) {
        this.idaviamento = idaviamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(String unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }
    public Set getFaccaos() {
        return this.faccaos;
    }
    
    public void setFaccaos(Set faccaos) {
        this.faccaos = faccaos;
    }




}


