package ufg.inf.pw.model;
// Generated Jun 9, 2015 1:36:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aviamento generated by hbm2java
 */
public class Aviamento  implements java.io.Serializable {


     private Integer idaviamento;
     private String nome;
     private String unidadeMedida;
     private Set suprimentos = new HashSet(0);

    public Aviamento() {
    }

    public Aviamento(String nome, String unidadeMedida, Set suprimentos) {
       this.nome = nome;
       this.unidadeMedida = unidadeMedida;
       this.suprimentos = suprimentos;
    }
   
    public Integer getIdaviamento() {
        return this.idaviamento;
    }
    
    public void setIdaviamento(Integer idaviamento) {
        this.idaviamento = idaviamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(String unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }
    public Set getSuprimentos() {
        return this.suprimentos;
    }
    
    public void setSuprimentos(Set suprimentos) {
        this.suprimentos = suprimentos;
    }




}


