package ufg.inf.pw.model;
// Generated Jul 9, 2015 7:28:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aviamento generated by hbm2java
 */
public class Aviamento  implements java.io.Serializable {


     private Integer idaviamento;
     private Unidade unidade;
     private String nome;
     private Set suprimentos = new HashSet(0);

    public Aviamento() {
    }

    public Aviamento(Unidade unidade, String nome, Set suprimentos) {
       this.unidade = unidade;
       this.nome = nome;
       this.suprimentos = suprimentos;
    }
   
    public Integer getIdaviamento() {
        return this.idaviamento;
    }
    
    public void setIdaviamento(Integer idaviamento) {
        this.idaviamento = idaviamento;
    }
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getSuprimentos() {
        return this.suprimentos;
    }
    
    public void setSuprimentos(Set suprimentos) {
        this.suprimentos = suprimentos;
    }




}


