package ufg.inf.pw.model;
// Generated Jul 9, 2015 7:28:52 PM by Hibernate Tools 4.3.1



/**
 * Corte generated by hbm2java
 */
public class Corte  implements java.io.Serializable {


     private Integer idcorte;
     private Modelo modelo;
     private String nome;
     private String foto;

    public Corte() {
    }

    public Corte(Modelo modelo, String nome, String foto) {
       this.modelo = modelo;
       this.nome = nome;
       this.foto = foto;
    }
   
    public Integer getIdcorte() {
        return this.idcorte;
    }
    
    public void setIdcorte(Integer idcorte) {
        this.idcorte = idcorte;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


