package ufg.inf.pw.model;
// Generated Apr 30, 2015 2:48:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Faccao generated by hbm2java
 */
public class Faccao  implements java.io.Serializable {


     private int idfaccao;
     private Faccionista faccionista;
     private Date dataEntrega;
     private Date dataColeta;
     private Set pecas = new HashSet(0);
     private Set aviamentos = new HashSet(0);

    public Faccao() {
    }

	
    public Faccao(int idfaccao) {
        this.idfaccao = idfaccao;
    }
    public Faccao(int idfaccao, Faccionista faccionista, Date dataEntrega, Date dataColeta, Set pecas, Set aviamentos) {
       this.idfaccao = idfaccao;
       this.faccionista = faccionista;
       this.dataEntrega = dataEntrega;
       this.dataColeta = dataColeta;
       this.pecas = pecas;
       this.aviamentos = aviamentos;
    }
   
    public int getIdfaccao() {
        return this.idfaccao;
    }
    
    public void setIdfaccao(int idfaccao) {
        this.idfaccao = idfaccao;
    }
    public Faccionista getFaccionista() {
        return this.faccionista;
    }
    
    public void setFaccionista(Faccionista faccionista) {
        this.faccionista = faccionista;
    }
    public Date getDataEntrega() {
        return this.dataEntrega;
    }
    
    public void setDataEntrega(Date dataEntrega) {
        this.dataEntrega = dataEntrega;
    }
    public Date getDataColeta() {
        return this.dataColeta;
    }
    
    public void setDataColeta(Date dataColeta) {
        this.dataColeta = dataColeta;
    }
    public Set getPecas() {
        return this.pecas;
    }
    
    public void setPecas(Set pecas) {
        this.pecas = pecas;
    }
    public Set getAviamentos() {
        return this.aviamentos;
    }
    
    public void setAviamentos(Set aviamentos) {
        this.aviamentos = aviamentos;
    }




}


