package ufg.inf.pw.model;
// Generated Jul 9, 2015 7:28:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Faccao generated by hbm2java
 */
public class Faccao  implements java.io.Serializable {


     private Integer idfaccao;
     private Faccionista faccionista;
     private Date dataEntrega;
     private Date dataColeta;
     private Set pecas = new HashSet(0);
     private Set suprimentos = new HashSet(0);

    public Faccao() {
    }

    public Faccao(Faccionista faccionista, Date dataEntrega, Date dataColeta, Set pecas, Set suprimentos) {
       this.faccionista = faccionista;
       this.dataEntrega = dataEntrega;
       this.dataColeta = dataColeta;
       this.pecas = pecas;
       this.suprimentos = suprimentos;
    }
   
    public Integer getIdfaccao() {
        return this.idfaccao;
    }
    
    public void setIdfaccao(Integer idfaccao) {
        this.idfaccao = idfaccao;
    }
    public Faccionista getFaccionista() {
        return this.faccionista;
    }
    
    public void setFaccionista(Faccionista faccionista) {
        this.faccionista = faccionista;
    }
    public Date getDataEntrega() {
        return this.dataEntrega;
    }
    
    public void setDataEntrega(Date dataEntrega) {
        this.dataEntrega = dataEntrega;
    }
    public Date getDataColeta() {
        return this.dataColeta;
    }
    
    public void setDataColeta(Date dataColeta) {
        this.dataColeta = dataColeta;
    }
    public Set getPecas() {
        return this.pecas;
    }
    
    public void setPecas(Set pecas) {
        this.pecas = pecas;
    }
    public Set getSuprimentos() {
        return this.suprimentos;
    }
    
    public void setSuprimentos(Set suprimentos) {
        this.suprimentos = suprimentos;
    }




}


