package ufg.inf.pw.model;
// Generated Jun 3, 2015 1:24:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private Integer idmodelo;
     private String nome;
     private String descricao;
     private String foto;
     private Set pecas = new HashSet(0);
     private Set cortes = new HashSet(0);

    public Modelo() {
    }

    public Modelo(String nome, String descricao, String foto, Set pecas, Set cortes) {
       this.nome = nome;
       this.descricao = descricao;
       this.foto = foto;
       this.pecas = pecas;
       this.cortes = cortes;
    }
   
    public Integer getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(Integer idmodelo) {
        this.idmodelo = idmodelo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getPecas() {
        return this.pecas;
    }
    
    public void setPecas(Set pecas) {
        this.pecas = pecas;
    }
    public Set getCortes() {
        return this.cortes;
    }
    
    public void setCortes(Set cortes) {
        this.cortes = cortes;
    }




}


