package ufg.inf.pw.model;
// Generated Jun 4, 2015 12:12:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Peca generated by hbm2java
 */
public class Peca  implements java.io.Serializable {


     private Integer idpeca;
     private Modelo modelo;
     private String nome;
     private Integer quantidade;
     private Set faccaos = new HashSet(0);

    public Peca() {
    }

    public Peca(Modelo modelo, String nome, Integer quantidade, Set faccaos) {
       this.modelo = modelo;
       this.nome = nome;
       this.quantidade = quantidade;
       this.faccaos = faccaos;
    }
   
    public Integer getIdpeca() {
        return this.idpeca;
    }
    
    public void setIdpeca(Integer idpeca) {
        this.idpeca = idpeca;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Set getFaccaos() {
        return this.faccaos;
    }
    
    public void setFaccaos(Set faccaos) {
        this.faccaos = faccaos;
    }




}


