package ufg.inf.pw.model;
// Generated Jun 4, 2015 12:12:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Suprimento generated by hbm2java
 */
public class Suprimento  implements java.io.Serializable {


     private Integer idsuprimento;
     private Aviamento aviamento;
     private Integer quantidade;
     private Set faccaos = new HashSet(0);

    public Suprimento() {
    }

    public Suprimento(Aviamento aviamento, Integer quantidade, Set faccaos) {
       this.aviamento = aviamento;
       this.quantidade = quantidade;
       this.faccaos = faccaos;
    }
   
    public Integer getIdsuprimento() {
        return this.idsuprimento;
    }
    
    public void setIdsuprimento(Integer idsuprimento) {
        this.idsuprimento = idsuprimento;
    }
    public Aviamento getAviamento() {
        return this.aviamento;
    }
    
    public void setAviamento(Aviamento aviamento) {
        this.aviamento = aviamento;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Set getFaccaos() {
        return this.faccaos;
    }
    
    public void setFaccaos(Set faccaos) {
        this.faccaos = faccaos;
    }




}


