package ufg.inf.pw.model;
// Generated Jul 9, 2015 7:28:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unidade generated by hbm2java
 */
public class Unidade  implements java.io.Serializable {


     private Integer idunidade;
     private String nome;
     private Set aviamentos = new HashSet(0);

    public Unidade() {
    }

    public Unidade(String nome, Set aviamentos) {
       this.nome = nome;
       this.aviamentos = aviamentos;
    }
   
    public Integer getIdunidade() {
        return this.idunidade;
    }
    
    public void setIdunidade(Integer idunidade) {
        this.idunidade = idunidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getAviamentos() {
        return this.aviamentos;
    }
    
    public void setAviamentos(Set aviamentos) {
        this.aviamentos = aviamentos;
    }




}


